version: '3.8'
services:
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    environment:
      POSTGRES_USER: vectoruser
      POSTGRES_PASSWORD: vectorpass
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    restart: unless-stopped